### ISSUE TITLE
Feature Request: Update to Nancy Version 2.0.

### ISSUE THREAD

**Issue by Jaxelr** [Zaid-Ajaj/Nancy.Serilog#4]
Greetings, since Nancy threw a newer version of their lib, could we get an updated version targeting Nancy 2.0?

Perhaps move Nancy.Serilog lib to depend on Nancy 2.0 and deprecate Nancy.Serilog.Core? 

Any feedback would be appreciated, also i could help with PR if necessary.

**Comment by Zaid-Ajaj** [comment]
Hello there, yeah I heard the news about the stable release of Nancy! My plan is indeed to deprecate `Nancy.Serilog.Core` and publish just as `Nancy.Serilog` instead. I will be able to work on it soon, probably this weekend since I wanted to clean up this repo a bit for while, so this is the right occasion :smile:

**Comment by Zaid-Ajaj** [comment]
Just revamped the whole repository from scratch, built and published `Nancy.Serilog` as version 2.0 to nuget. Would be really cool if you could take it for a spin when nuget finished it's magic ;)
